// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYy7_v8r4QpACN0q24oZmhToIjw4WBK1U',
    appId: '1:75545960528:web:69eb26e266d077e6403155',
    messagingSenderId: '75545960528',
    projectId: 'coach-link-e598e',
    authDomain: 'coach-link-e598e.firebaseapp.com',
    storageBucket: 'coach-link-e598e.appspot.com',
    measurementId: 'G-LQXFGJF6LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhbpunSj0io_-XITbuYidCyfIReHqv4rg',
    appId: '1:75545960528:android:dc707ed738e87be4403155',
    messagingSenderId: '75545960528',
    projectId: 'coach-link-e598e',
    storageBucket: 'coach-link-e598e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyhWjc7f_iGXyraLq4yWftMqN-QXF2qSI',
    appId: '1:75545960528:ios:5d7923bf86e66aec403155',
    messagingSenderId: '75545960528',
    projectId: 'coach-link-e598e',
    storageBucket: 'coach-link-e598e.appspot.com',
    iosClientId: '75545960528-illapmlauqo33q0m2togh74cb54h0ve3.apps.googleusercontent.com',
    iosBundleId: 'com.example.coachLink',
  );
}
