// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02MSbMWw8Fymr2q-4jNJk42twbpFrJa0',
    appId: '1:230240573376:web:f39f3c602b143b81e2da25',
    messagingSenderId: '230240573376',
    projectId: 'coach-link-staging',
    authDomain: 'coach-link-staging.firebaseapp.com',
    databaseURL: 'https://coach-link-staging-default-rtdb.firebaseio.com',
    storageBucket: 'coach-link-staging.appspot.com',
    measurementId: 'G-PY32KSDSX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpYOE3GDfXzDot4oXb1s5wi9JF44LwCI',
    appId: '1:230240573376:android:6be399013b6ed5f1e2da25',
    messagingSenderId: '230240573376',
    projectId: 'coach-link-staging',
    databaseURL: 'https://coach-link-staging-default-rtdb.firebaseio.com',
    storageBucket: 'coach-link-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLxymxMh51KFcYfcp7iwvo7qj0vDoMrV8',
    appId: '1:230240573376:ios:723313d1781aa84ae2da25',
    messagingSenderId: '230240573376',
    projectId: 'coach-link-staging',
    databaseURL: 'https://coach-link-staging-default-rtdb.firebaseio.com',
    storageBucket: 'coach-link-staging.appspot.com',
    iosClientId: '230240573376-k1ldej76m1s3593ookrdra5r2sesb12c.apps.googleusercontent.com',
    iosBundleId: 'com.example.coachLink',
  );
}
